### ISSUE TITLE
pisteenlasku

### ISSUE THREAD

**Issue by aspehkonen** [rikuw/palloilumoninpeli#12]
kun pallo menee "maaliin"

**Comment by rikuw** [comment]
Saatiin tehtyä silleen että serveri tietää koska pallo menee maaliin, ei ehditty vielä tehdä sillä mitään, commit: 4af4242ed815e984d7e425d5907080f47acfd557

**Comment by aspehkonen** [comment]
pelaajille annettiin elämät, jotka vähenevät, kun pallo menee maaliin
